### PR TITLE
Anchor rtl text to the right

### LINKED ISSUE #1408: Arabic text display does not float/anchor to the right
For example:

Screen Shot 2022-11-07 at 11 46 08 AM

### PR DESCRIPTION
**Pull request by taylor-yamashita**
Closes #1408

### CODE REVIEW

**Comment by taylor-yamashita** [comment]
Shorter title: 
Screen Shot 2023-02-03 at 11 38 17 AM
Screen Shot 2023-02-03 at 11 38 24 AM

**Comment by taylor-yamashita** [comment]
Longer title:
Screen Shot 2023-02-03 at 11 40 48 AM
Screen Shot 2023-02-03 at 11 41 01 AM

**Comment by taylor-yamashita** [comment]
Some shorter pieces of rtl text in the metadata section start to look very far away from the section headers (see screenshots)—is this okay? Wouldn't really know how to change this besides making the metadata section narrower, which would change a lot.

**Comment by taylor-yamashita** [comment]
Even longer title:
Screen Shot 2023-02-03 at 11 44 32 AM
Screen Shot 2023-02-03 at 11 44 40 AM

**Review by eliotjordan — APPROVED** [review]

**Comment by eliotjordan** [comment]
This looks good, but I'll wait for others to take a look before merging. That "Edit" button conflict from the ticket doesn't appear to be an issue anymore. Can someone confirm?

**Comment by kelea99** [comment]
@eliotjordan and @taylor-yamashita 

- incipit and colophon look great (screenshot 1)
- Titles - short and long at top of screen: Fantastico!
-  Metatdata below viewer: I see what you are saying, Taylor and do agree, however I dont see a better way forward without completely changing they margins and that is a larger conversation I don't think we have the bandwidth for. So, I'm saying its the best option we have and it looks great!!!

I say go. Anyone else want to chime in?

**Comment by jpstroop** [comment]
🎉

**Pull request merged**
