### PR TITLE
Add Plausible.io analytics

### LINKED ISSUE #1532: Add Plausible.IO
## Acceptance Criteria

- [x] There's a section in Plausible for DPUL
- [ ] Initial metrics are being gathered for DPUL.

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #1532

### CODE REVIEW

**Review by tpendragon — APPROVED** [review]

**Review by tpendragon — CHANGES_REQUESTED** [review]
Can we keep both for now?

**Comment by eliotjordan** [comment]
@tpendragon Added GA back.

**Review by hackartisan — COMMENTED** [review]
should this be different for staging?

**Comment by eliotjordan** [comment]
@hackartisan We don't have analytics setup for staging in GA or Plausible.

https://github.com/pulibrary/dpul/blob/main/app/views/layouts/spotlight/base.html.erb#L26

**Comment by hackartisan** [comment]
👍🏻 @eliotjordan yep looks right thank you!

**Review by hackartisan — APPROVED** [review]

**Review by tpendragon — APPROVED** [review]

**Pull request merged**
